In [11]:
import pandas as pd

Import pandas and read in the population_by_county.csv file into a dataframe called pop.

In [12]:
pop = pd.read_csv('population_by_county.csv')

 Show the head of the dataframe, Also show top 8 rows of the dataframe using head

In [7]:
pop.head(9)

             County           State  2010Census  2017PopEstimate
0  Abbeville County  South Carolina       25417            24722
1     Acadia Parish       Louisiana       61773            62590
2   Accomack County        Virginia       33164            32545
3        Ada County           Idaho      392365           456849
4      Adair County            Iowa        7682             7054
5      Adair County        Kentucky       18656            19485
6      Adair County        Missouri       25607            25377
7      Adair County        Oklahoma       22683            21909
8      Adams County        Colorado      441603           503167

What are the column names?

In [9]:
list(pop.columns)

['County', 'State', '2010Census', '2017PopEstimate']

How many States are represented in this data set?

In [9]:

print(len(set(pop['State'])))

51

 Get a list or array of all the states in the data set.

In [23]:
pop['State'].unique()

<StringArray>
[      'South Carolina',            'Louisiana',             'Virginia',
                'Idaho',                 'Iowa',             'Kentucky',
             'Missouri',             'Oklahoma',             'Colorado',
             'Illinois',              'Indiana',          'Mississippi',
             'Nebraska',         'North Dakota',                 'Ohio',
         'Pennsylvania',           'Washington',            'Wisconsin',
              'Vermont',            'Minnesota',              'Florida',
       'North Carolina',           'California',             'New York',
              'Wyoming',             'Michigan',               'Alaska',
             'Maryland',               'Kansas',            'Tennessee',
                'Texas',                'Maine',              'Arizona',
              'Georgia',             'Arkansas',           'New Jersey',
         'South Dakota',              'Alabama',               'Oregon',
        'West Virginia',        'Massachusetts',                 'Utah',
              'Montana',        'New Hampshire',           'New Mexico',
         'Rhode Island',               'Nevada', 'District of Columbia',
          'Connecticut',               'Hawaii',             'Delaware']
Length: 51, dtype: str

What are the five most common County names in the U.S.?

In [25]:
pop['County'].value_counts().head(5)

County
Washington County    30
Jefferson County     25
Franklin County      24
Jackson County       23
Lincoln County       23
Name: count, dtype: int64

What are the top 5 most populated Counties according to the 2010 Census?

In [54]:
pop_county = pop.sort_values(by='2010Census',ascending=False).head(5)
pop_county['County']

1713    Los Angeles County
628            Cook County
1209         Harris County
1784       Maricopa County
2501      San Diego County
Name: County, dtype: str

9. How many Counties have 2010 populations greater than 1 million?

In [17]:
len(pop[pop['2010Census'] > 1000000])

39

10. How many Counties don't have the word "County" in their name?

In [66]:
#pop['County'].filter(items=[])
pop[~pop['County'].str.contains('County')]

,County,State,2010Census,2017PopEstimate,population_pct
1,Acadia Parish,Louisiana,61773,62590,1.322584
32,Aleutians East Borough,Alaska,3141,3370,7.290672
33,Aleutians West Census Area,Alaska,5561,5763,3.632440
36,Alexandria city,Virginia,139966,160035,14.338482
50,Allen Parish,Louisiana,25764,25621,-0.555038
...,...,...,...,...,...
3071,Winchester city,Virginia,26203,27932,6.598481
3076,Winn Parish,Louisiana,15313,14311,-6.543460
3104,Wrangell City and Borough,Alaska,2369,2521,6.416209
3116,Yakutat City and Borough,Alaska,662,605,-8.610272
3136,Yukon-Koyukuk Census Area,Alaska,5588,5365,-3.990694

11. Add a column that calculates the percent change between the 2010 Census and the 2017 Population Estimate

In [42]:
population_pct = ((pop['2017PopEstimate']-pop['2010Census'])*100)/pop['2010Census']
pop['population_pct'] = population_pct
pop.head()

,County,State,2010Census,2017PopEstimate,population_pct
0,Abbeville County,South Carolina,25417,24722,-2.734390
1,Acadia Parish,Louisiana,61773,62590,1.322584
2,Accomack County,Virginia,33164,32545,-1.866482
3,Ada County,Idaho,392365,456849,16.434697
4,Adair County,Iowa,7682,7054,-8.174954

12. What States have the highest estimated percent change between the 2010 Census and the 2017 Population Estimate?

In [47]:
pop.sort_values(by='population_pct',ascending=False).head(5)

,County,State,2010Census,2017PopEstimate,population_pct
1861,McKenzie County,North Dakota,6360,12724,100.062893
1720,Loving County,Texas,82,134,63.414634
3060,Williams County,North Dakota,22398,33349,48.892758
1230,Hays County,Texas,157107,214485,36.521606
2944,Wasatch County,Utah,23530,32106,36.447089